# promptest.config.yaml
provider: openrouter
model: google/gemini-2.0-flash-lite-001
apiKey: ${OPENROUTER_API_API_KEY}
baseUrl: http://localhost:8100
srcDir: D:/usthaan/usthaan-lekha/src/app
testDir: ./example
headless: false