import { readFile } from 'fs/promises'
import { glob } from 'glob'
import path from 'path'

export interface ExtractedElement {
  description: string  // natural language — generated by AI later
  rawHtml: string      // the actual HTML element string
  selector: string     // best selector extracted directly from attributes
  elementType: string  // input | button | select | link | dropdown
  sourceFile: string
}

// File patterns that contain HTML across every major framework
const HTML_PATTERNS = [
  '**/*.component.html',   // Angular
  '**/*.html',             // plain HTML, Blade, Django, Rails
  '**/*.tsx',              // React, Next.js
  '**/*.jsx',              // React (older)
  '**/*.vue',              // Vue
  '**/*.svelte',           // Svelte
]

const IGNORE_PATTERNS = [
  '**/node_modules/**',
  '**/dist/**',
  '**/build/**',
  '**/.git/**',
  '**/*.spec.*',
  '**/*.test.*',
  '**/*.d.ts',
]

// Regex patterns to find interactive elements in HTML/JSX/template strings
const ELEMENT_PATTERNS = [
  // input fields
  /<input\b[^>]*>/gi,
  // buttons
  /<button\b[^>]*>[\s\S]*?<\/button>/gi,
  // select dropdowns
  /<select\b[^>]*>[\s\S]*?<\/select>/gi,
  // links
  /<a\b[^>]*>[\s\S]*?<\/a>/gi,
  // Angular material / custom components
  /<mat-select\b[^>]*>[\s\S]*?<\/mat-select>/gi,
  /<mat-input\b[^>]*>[\s\S]*?<\/mat-input>/gi,
]

// Extract the best CSS selector from an element's raw HTML string
function extractSelector(raw: string): string | null {
  // data-testid first
  const testId = raw.match(/data-testid=["']([^"']+)["']/)
  if (testId) return `[data-testid="${testId[1]}"]`

  // id
  const id = raw.match(/\bid=["']([^"']+)["']/)
  if (id) return `#${id[1]}`

  // name
  const name = raw.match(/\bname=["']([^"']+)["']/)
  if (name) return `[name="${name[1]}"]`

  // aria-label
  const aria = raw.match(/aria-label=["']([^"']+)["']/)
  if (aria) return `[aria-label="${aria[1]}"]`

  // formControlName (Angular)
  const fcn = raw.match(/formControlName=["']([^"']+)["']/)
  if (fcn) return `[formcontrolname="${fcn[1]}"]`

  // type
  const type = raw.match(/\btype=["']([^"']+)["']/)
  if (type) {
    const tag = raw.match(/^<(\w+)/)
    return `${tag?.[1] ?? 'input'}[type="${type[1]}"]`
  }

  // class (last resort — take first meaningful class)
  const cls = raw.match(/\bclass=["']([^"']+)["']/)
  if (cls) {
    const firstClass = cls[1].trim().split(/\s+/)[0]
    if (firstClass && !firstClass.startsWith('ng-')) return `.${firstClass}`
  }

  return null
}

// Get element type from raw HTML
function getElementType(raw: string): string {
  const tag = raw.match(/^<(\w[\w-]*)/)?.[1]?.toLowerCase() ?? ''
  if (tag === 'input') {
    const type = raw.match(/type=["']([^"']+)["']/)?.[1]?.toLowerCase()
    if (type === 'password') return 'password input'
    if (type === 'email')    return 'email input'
    if (type === 'submit')   return 'submit button'
    if (type === 'checkbox') return 'checkbox'
    return 'text input'
  }
  if (tag === 'button')     return 'button'
  if (tag === 'select' || tag === 'mat-select') return 'dropdown'
  if (tag === 'a')          return 'link'
  return tag
}

// Get visible text or placeholder from raw HTML
function getLabel(raw: string): string {
  const placeholder = raw.match(/placeholder=["']([^"']+)["']/)?.[1]
  if (placeholder) return placeholder

  const ariaLabel = raw.match(/aria-label=["']([^"']+)["']/)?.[1]
  if (ariaLabel) return ariaLabel

  const text = raw.replace(/<[^>]+>/g, '').trim().slice(0, 60)
  if (text) return text

  const name = raw.match(/\bname=["']([^"']+)["']/)?.[1]
  if (name) return name

  const formControl = raw.match(/formControlName=["']([^"']+)["']/)?.[1]
  if (formControl) return formControl

  return ''
}

export async function crawlCodebase(srcDir: string): Promise<ExtractedElement[]> {
  console.log(`[CRAWLER] Scanning: ${srcDir}`)

  // Find all files matching HTML patterns
  const files: string[] = []
  for (const pattern of HTML_PATTERNS) {
    const found = await glob(pattern, {
      cwd: srcDir,
      ignore: IGNORE_PATTERNS,
      posix: true,
      absolute: true,
    })
    files.push(...found)
  }

  // Deduplicate
  const uniqueFiles = [...new Set(files)]
  console.log(`[CRAWLER] Found ${uniqueFiles.length} files with HTML content`)

  const elements: ExtractedElement[] = []

  for (const filePath of uniqueFiles) {
    try {
      const content = await readFile(filePath, 'utf-8')
      const relative = path.relative(srcDir, filePath)

      for (const pattern of ELEMENT_PATTERNS) {
        const matches = content.match(pattern) ?? []
        for (const raw of matches) {
          const selector = extractSelector(raw)
          if (!selector) continue  // skip elements we can't reliably target

          const elementType = getElementType(raw)
          const label       = getLabel(raw)

          // Build a rough natural language description from what we know
          // AI will refine these during init-memory
          const description = label
            ? `${label} ${elementType}`
            : `${elementType} in ${path.basename(filePath, path.extname(filePath))}`

          elements.push({
            description: description.toLowerCase().trim(),
            rawHtml:     raw.slice(0, 200),  // keep it short
            selector,
            elementType,
            sourceFile:  relative,
          })
        }
      }
    } catch {
      // skip unreadable files
    }
  }

  // Deduplicate by selector
  const seen = new Set<string>()
  const unique = elements.filter(e => {
    if (seen.has(e.selector)) return false
    seen.add(e.selector)
    return true
  })

  console.log(`[CRAWLER] Extracted ${unique.length} unique interactive elements`)
  return unique
}